### ISSUE TITLE
AzureBlobFileStorage.GetSize() always returns -1

### ISSUE THREAD

**Issue by pedropaf** [pofider/AzureBlobFileSystem#2]
I think that this can be easily fixed retrieving the metadata in the class constructor:

// Set options for the request. E.g., Specify an operation timeout of 20 seconds.
BlobRequestOptions options = new BlobRequestOptions();

options.Timeout = TimeSpan.FromSeconds(20.0);

// Populate the blob's attributes.
blob.FetchAttributes(options);

Great work!

**Comment by pofider** [comment]
Thanks for your bug report.

I was not sure about doing such long work in constructor and rather call FetchAttributes lazily before GetSize.

Fix released in nuget 0.0.6
