### ISSUE TITLE
How about a wrapper to do both local and cloud for uploads?

### ISSUE THREAD

**Issue by rdefreitas** [pofider/AzureBlobFileSystem#5]
So I came up with a little bit of async support, as well as an IUploadService wrapper that allows you to specify, say "~/uploads" as your target for a local copy of a file, store it from HttpPostedFileBase, and would allow you to spin up a background task automatically to copy that file to your azure account when requesting the URL.

Would you be interested in adding this stuff to the repository? It spins up the background thread using HostingEnvironment.QueueBackgroundWorkItem, so it would require 4.5.2 instead of 4.5

**Comment by pofider** [comment]
Async support would be great.

Maybe I am wrong, but not sure with IUploadService wrapper you mentioned. It looks it doesn't fit to the main idea of this library which is to create an interchangeable abstraction over File System / Azure Blob Storage.

**Comment by rondefreitas** [comment]
Just closing this out as I not only unfortunately abandoned this but don't have the code anymore at th9is point
